name: envify_generator
description: Code generator for envify, a better tool to handle environment variables.
version: 2.0.2
homepage: https://github.com/frencojobs/envify
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  build: ^2.0.1
  dotenv: ^3.0.0
  envify:
    path: '../envify'
  path: ^1.8.0
  source_gen: ^1.0.0

dev_dependencies:
  lint: ^1.5.3
  source_gen_test: ^1.0.0
  test: ^1.19.5

scripts: ../derry.yaml
